defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:14
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS

version: 2.1
jobs:
  test:
    parameters:
      image:
        description: "node version"
        default: "latest"
        type: string
    working_directory: ~/app
    docker:
      - image: "circleci/node:<<parameters.image>>"
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - run: node -v
      - run: npm i --force
      - run: npm t
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npm run lint -- --plugin log
  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set NPM tokens
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Install published
          command: npx published --git-tag
  glossary:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Add to Glossary
          command: |
            curl --user ${CIRCLECI_API_TOKEN}: \
              --header "Content-Type: application/json" \
              --data "{\"build_parameters\":{\"TRIGGERING_REPOSITORY\":\"${CIRCLE_REPOSITORY_URL}\"}}" \
              --request POST \
              https://circleci.com/api/v1.1/project/github/fiverr/glossary/tree/master

workflows:
  version: 2.1
  ci-cd:
    jobs:
      - lint:
          context: org-global
      - test:
          context: org-global
          matrix:
            parameters:
              image:
                - "10"
                - "12"
                - "14"
      - publish:
          context: org-global
          requires:
            - test
            - lint
      - glossary:
          context: org-global
          requires:
            - publish
          filters:
            branches:
              only:
                - master

experimental:
  notify:
    branches:
      only:
        - master
